export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const LOAD_LOCATIONS_SUCCESS = 'LOAD_ROUTES_SUCCESS';
export const CREATE_LOCATION_SUCCESS = 'CREATE_ROUTE_SUCCESS';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_ROUTE_SUCCESS';
export const SELECT_LOCATION_SUCCESS = 'SELECT_ROUTE_SUCCESS';
export const SELECT_LOCATION_ERROR = 'SELECT_LOCATION_ERROR';


export const LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';



